#!/bin/bash
curl -s https://ca.dn42.us/reg/filter6.txt | \
	awk '/^[0-9]/ && $2 ~ /permit/ {printf "%s{%s,%s}\n", $3, $4, $5}' | \
	awk 'BEGIN {printf "function is_valid_network() {\n return net ~ [\n"} \
		NR > 1 {printf ",\n"} {printf "  %s", $1}
		END {printf "\n ];\n}\n"}'
