#!/bin/bash
# Just copied from dn42 wiki
curl -sk https://dn42.us/git/dn42/registry/plain/data/filter.txt | \
  awk 'BEGIN {printf "function is_valid_network() {\n return net ~ [\n" } \
       /^[0-9]/ && $2 ~ /permit/ {printf " %s{%s,%s},\n", $3, $4, $5};' | \
  sed "$ s/,$/\n ];\n}/" > /etc/bird/filter4.conf
