#!/bin/bash

rtfile="/etc/openvpn/routes/default"

# Put v4 routes into route file
birdc show route | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\/[0-9]+'| netmaskfromcidr | awk '{printf "push \"route %s %s\"\n", $1, $2}' > "$rtfile"
# Put v6 routes into route file
# v6 regex copied from stackoverflow
birdc6 show route | grep -Po '^(?>(?>([a-f\d]{1,4})(?>:(?1)){3}|(?!(?:.*[a-f\d](?>:|$)){})((?1)(?>:(?1)){0,6})?::(?2)?)|(?>(?>(?1)(?>:(?1)){5}:|(?!(?:.*[a-f\d]:){6,})(?3)?::(?>((?1)(?>:(?1)){0,4}):)?)?(25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)(?>\.(?4)){3}))\/\d{1,2}' | awk '{printf "push \"route-ipv6 %s\"\n", $0}' >> "$rtfile"

echo "Got $(wc -l "$rtfile" | awk '{ printf $1 }') routes"
